# Generated by Django 4.1.1 on 2022-09-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='articles',
            field=models.ManyToManyField(to='myapi.article'),
        ),
    ]
