# Generated by Django 4.1.1 on 2022-09-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_article_options_alter_articletype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={},
        ),
    ]
