# Generated by Django 4.1.1 on 2022-09-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_article_options_alter_articletype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='articles',
            field=models.ManyToManyField(related_name='types', to='myapi.article'),
        ),
    ]
