# Generated by Django 4.1.1 on 2022-09-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_type_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.type'),
        ),
    ]
